version: 2
jobs:
  build:
    machine:
        enabled: true
        image: circleci/classic:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build the Distribution
          command: |
            virtualenv .venv
            . .venv/bin/activate
            pip install -U pip setuptools
            pip install -r requirements.txt
            pip install -r requirements.dev.txt
            src/bin/maintenance/build-wheel.py indico --add-version-suffix --ignore-unclean