# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build the Distribution
          command: |
            pip install virtualenv
            virtualenv .venv
            . .venv/bin/activate
            pip install -r src/requirements.txt
            pip install -r src/requirements.dev.txt
            src/bin/maintenance/build-wheel.py indico --add-version-suffix