# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine:
      - image: circleci/classic:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            yum install -y python-devel python-virtualenv libjpeg-turbo-devel libxslt-devel libxml2-devel libffi-devel pcre-devel libyaml-devel
      - run:
          name: Build the Distribution
          command: |
            virtualenv .venv
            . .venv/bin/activate
            pip install -r src/requirements.txt
            pip install -r src/requirements.dev.txt
            src/bin/maintenance/build-wheel.py indico --add-version-suffix